### ISSUE TITLE
Currently it does not work with Manufacturing Edition Transactions

### ISSUE THREAD

**Issue by dgodsill** [Acumatica/Acumatica-LotSerialNbrAttribute#2]
The custom Allocations form would have to be implemented for the Move/Labor, Materials (for byproducts), and disassembly.

Additionally, the it would be useful to have the sales order lookup added to the Materials form to lookup an material to issue by attribute.  

Inventory Lot/Serial History would also benefit for the same lookup.

**Comment by Jpotoka** [comment]
Any Chance this customization package will be updated to work with the manufacturing edition?

**Comment by dgodsill** [comment]
It would not be considered until it is an Acumatica feature.

**Comment by DhirenChhapgar** [comment]
No, we cannot add support for Manufacturing Edition as part of this customization package since it will make Acumatica-LotSerialNbrAttribute customization package dependent on Manufacturing Edition. 

However, Acumatica-LotSerialNbrAttribute customization is available as open source under MIT license and by referring this solution, one can develop/extend similar Lot/Serial Attribute support for Manufacturing Edition modules in a separate customization project.
